services:
  redis:
    image: redis
    ports:
      - 6379:6379
  redistest:
    image: redistest
    ports:
      - 80:8080
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis